[project]
name = "shoplytics"
version = "0.1.0"
description = "Interactive business analytics system for small retail of children's and teenage clothing"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["streamlit>=1.45.0"]
